
# segment defines a ellipsoid in the maximal range of the x and y dimensions
# ellipsoid a,b,c

[[segment]]
# x/a dimension
x_start=-10
x_start_min=0
x_end_min=0
x_end=+10
# y/b dimension
y_start=-10
y_start_min=0
y_end_min=0
y_end=+10
# y/b dimension
z_start=-10
z_start_min=0
z_end_min=0
z_end=+10
count=1000 # count of elements
density=0.5 # elements per 1^3

[[segment]]
# x/a dimension
x_start=-20
x_start_min=10
x_end_min=10
x_end=+20
# y/b dimension
y_start=-20
y_start_min=10
y_end_min=10
y_end=+20
# z/c dimension
z_start=-20
z_start_min=10
z_end_min=10
z_end=+20
count=500 # count of elements
density=0.5 # elements per 1^3
	
[[segment]]
# x/a dimension
x_start=-30
x_start_min=20
x_end_min=20
x_end=+30
# y/b dimension
y_start=-30
y_start_min=20
y_end_min=20
y_end=+30
# z/c dimension
z_start=-30
z_start_min=20
z_end_min=20
z_end=+30
count=250 # count of elements
density=0.5 # elements per 1^3



