
# segment defines a ellipsoid in the maximal range of the x and y dimensions
# ellipsoid a,b,c

[[segment]]
# x/a dimension
x_start=-10.0
x_start_min=0.0
x_end_min=0.0
x_end=+10.0
# y/b dimension
y_start=-10.0
y_start_min=0.0
y_end_min=0.0
y_end=+10.0
# y/b dimension
z_start=-10.0
z_start_min=0.0
z_end_min=0.0
z_end=+10.0
count=1000 # count of elements
density=0.5 # elements per 1^3

[[segment]]
# x/a dimension
x_start=-20.0
x_start_min=10.0
x_end_min=10.0
x_end=+20.0
# y/b dimension
y_start=-20.0
y_start_min=10.0
y_end_min=10.0
y_end=+20.0
# z/c dimension
z_start=-20.0
z_start_min=10.0
z_end_min=10.0
z_end=+20.0
count=500 # count of elements
density=0.5 # elements per 1^3
	
[[segment]]
# x/a dimension
x_start=-30.0
x_start_min=20.0
x_end_min=20.0
x_end=+30.0
# y/b dimension
y_start=-30.0
y_start_min=20.0
y_end_min=20.0
y_end=+30.0
# z/c dimension
z_start=-30.0
z_start_min=20.0
z_end_min=20.0
z_end=+30.0
count=250 # count of elements
density=0.5 # elements per 1^3



